{% set name = "condastats" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/condastats-{{ version }}.tar.gz
  sha256: c0ffc117851000d7e4dae9ad611d4cc8a1d3f6e4c0479aa66340e014209c0b1f

build:
  number: 0
  noarch: python
  entry_points:
    - condastats=condastats.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - dask >=2024.5.2
    - numpy >=1.20.0
    - pandas >=2.0.0
    - pyarrow >=10.0.0
    - python >={{ python_min }}
    - python-snappy >=0.6.1
    - s3fs >=2023.1.0

test:
  imports:
    - condastats
  commands:
    - pip check
    - condastats --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/conda-incubator/condastats
  summary: Conda package stats CLI
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://condastats.readthedocs.io

extra:
  recipe-maintainers:
    - sophiamyang
    - seibert
    - jezdez
