{% set name = "condastats" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/condastats-{{ version }}.tar.gz
  sha256: 08980d23dcd46495f6ce856ed9620c2f599f075c5f5d3c6957c88b0202154054

build:
  number: 0
  noarch: python
  entry_points:
    - condastats=condastats.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dask
    - pyarrow
    - fsspec >=2021.4.0
    - numpy >=1.16.5
    - python >={{ python_min }}
    - python-snappy
    - s3fs >=2021.4.0

test:
  imports:
    - condastats
  commands:
    - pip check
    - condastats --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sophiamyang/condastats
  summary: Conda package stats CLI
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: condastats.readthedocs.io

extra:
  recipe-maintainers:
    - sophiamyang
    - seibert
