{% set name = "condastats" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/condastats-{{ version }}.tar.gz
  sha256: 013dfb759b78fc7088411cdf55e015cda25888efee0e21b57c946a7c9d4afb36

build:
  number: 0
  noarch: python
  entry_points:
    - condastats=condastats.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dask
    - pyarrow
    - fsspec >=2021.4.0
    - numpy >=1.16.5
    - python >=3.6
    - python-snappy
    - s3fs >=2021.4.0

test:
  imports:
    - condastats
  commands:
    - pip check
    - condastats --help
  requires:
    - pip

about:
  home: https://github.com/sophiamyang/condastats
  summary: Conda package stats CLI
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: condastats.readthedocs.io

extra:
  recipe-maintainers:
    - sophiamyang
    - seibert
