{% set name = "condastats" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8342576216c06f1ba8e84c6aa1b45b390f3e810a745fcdb562df0380402367b6

build:
  noarch: python
  number: 0
  entry_points:
    - condastats=condastats.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - dask
    - fastparquet
    - python >=3.6
    - python-snappy
    - s3fs

test:
  imports:
    - condastats
  commands:
    - condastats --help

about:
  home: https://github.com/sophiamyang/condastats
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Conda package stats CLI
  doc_url: condastats.readthedocs.io

extra:
  recipe-maintainers:
    - sophiamyang
    - seibert
